name: Release

on:
  pull_request:
    branches: [ "master" ]
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract tag from PR title
        id: extract_tag
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          TAG=$(echo "$PR_TITLE" | sed -nE 's/^chore\(release\): ([0-9]+\.[0-9]+\.[0-9]+)$/v\1/p')

          if [[ -n "$TAG" ]]; then
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "PR title does not match release format. Skipping tag creation."
          fi

      - name: Create GitHub Release
        if: env.TAG != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false