name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Extract version from PR title
        id: extract_version
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pr_body="${{ github.event.pull_request.body }}"
          echo "PR Title: $pr_title"
          echo "PR Description: $pr_body"
          # Ищем в названии PR шаблон "Release vX.Y.Z"
          if [[ "$pr_title" =~ ^Release\ v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            version="${BASH_REMATCH[1]}"
            echo "Version found: $version"
            echo "VERSION=$version" >> $GITHUB_ENV
            echo "DESCRIPTION=$pr_body" >> $GITHUB_ENV
          else
            echo "No valid version found in PR title."
            exit 0  # Если версия не найдена, не продолжаем

      - name: Create a Release
        if: env.VERSION != ''
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
          gh release create ${{ env.VERSION }} --title "Release ${{ env.VERSION }}" --notes "${{ env.DESCRIPTION }}"
